# Generated by Django 3.2 on 2022-02-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='preschool',
            fields=[
                ('School_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=1000, null=True)),
                ('Facility', models.CharField(max_length=1000, null=True)),
                ('Ratings', models.FloatField(null=True)),
                ('City', models.CharField(max_length=1000, null=True)),
                ('Address', models.CharField(max_length=1000, null=True)),
                ('Link', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
